FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y vim cgdb gcc make

ARG SOURCE
ARG BINARY
ENV SOURCE=$SOURCE BINARY=$BINARY

RUN mkdir -p "$SOURCE"
ADD . "$SOURCE"
WORKDIR "$SOURCE"
RUN make

ENTRYPOINT "$SOURCE/$BINARY"

